config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # namespace :admin do
    #   resources :users
    #   resources :carts
    #   resources :items
    #   resources :item_to_carts
    #   resources :orders

    #   root to: "users#index"
    # end
	devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show, :edit, :update] do
  	resources :avatar, only: [:create]
  	resources :carts, only: [:show]
  	resources :items do
  		resources :item_to_carts
  	end
    resources :order
  end

  resources :confirmation, only: [:new, :create]
  
  post '/confirmation/new', to: 'confirmation#create'
  get '/presentation/team'
	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/confirmation.rb
class Confirmation < ApplicationRecord
end

app/controllers/SCOPE/confirmations_controller.rb
# frozen_string_literal: true

class SCOPE::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/confirmation_controller.rb
class ConfirmationController < ApplicationController
  def new
    @confirmation = Confirmation.new
  end
  
  def create
    @confirmations = Confirmation.where(email: session[:temp_email]).all

    respond_to do |format|
      if code_is_valid
        User.where(email: session[:temp_email]).first.update(is_validate: true)
        session.delete(:temp_email)
        format.html{
          redirect_to '/users/sign_in', notice: "Your account as been validate"
        }
      else
        format.html{
          render :new, alert: "This code is invalid, please check your email"
        }
      end
    end
  end

  private
  def code_is_valid
    @confirmations.each do |confirmation|
      return true if confirmation.confirmation_code == params[:confirmation_code]
    end
    return false
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/views/confirmation/_form.html.erb
<br><br><br><br><br><br><br><br><br><br>
<center>
<div class="confirmation_button">
  <%= form_for confirmation_index_path do |f| %>
  <!-- invalide token here -->
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <!-- end of token -->
  <div class="row text-center">
    <div class="col-sm">
      <div class="form-group">
        <label for="psw">

          <h3 style = "color:red; text-shadow: 1.5px 2px red">SECURITY</h3>
          <label style ="color:green;"><span class="glyphicon glyphicon-ok"></span> Un email vous a été envoyer</label> <br><br>
          <span class="glyphicon"></span>Avant de vous connecter, merci de confirmer votre compte</label><br>
          <input type="password" name = "confirmation_code" class="form-control" placeholder="code sent in your email" required>
      </div>
    </div>

      <button type="submit" class="btn btn-lg btn-primary btn-block"><span class="glyphicon glyphicon-ok">Confirmer</span></button>
  </div>
  <% end %>
</div>
</center>

app/views/confirmation/new.html.erb
	<%= render 'form', confirmation: @confirmation %>