config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # namespace :admin do
    #   resources :users
    #   resources :carts
    #   resources :items
    #   resources :item_to_carts
    #   resources :orders

    #   root to: "users#index"
    # end
	devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show, :edit, :update] do
  	resources :avatar, only: [:create]
  	resources :carts, only: [:show]
  	resources :items do
  		resources :item_to_carts
  	end
    resources :order
  end

  resources :confirmation, only: [:new, :create]
  
  post '/confirmation/new', to: 'confirmation#create'
  get '/presentation/team'
	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :orders
  has_one_attached :avatar

  after_create :send_confirmation_email

  # after_create :send_welcome_email

  def send_confirmation_email
    unless self.is_validate
      UserMailer.confirmation_email(self).deliver_now
    end
  end

  def send_welcome_email
  	unless self.is_validate
      UserMailer.welcome_email(self).deliver_now
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    @user.is_validate = false

    @confirmation = Confirmation.create(
      email: @user.email,
      confirmation_code: (6.times.map{ 200 + Random.rand(12) }).join('')
    )

    session[:temp_email] = @user.email

    if @user.save
      myCart = Cart.create(user_id: @user.id)
      redirect_to '/users/sign_in'
    else
      render :new
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    @email = params.require(:user).permit(:email)
    @user = User.where(@email).first
    
      if !@user
        redirect_to '/users/sign_in', alert: "Unknown email, try another"
      elsif !@user.is_validate
        redirect_to '/confirmation/new'
      else
        super
      end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  include UsersHelper
  before_action :authenticate_user
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.avatar.attach(params[:avatar]) if params[:avatar]
        format.html { redirect_to @user, notice: 'Users was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper

	def authenticate_user
		unless @user == current_user
			redirect_to '/'
		end
	end
end

app/views/users/_form.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-4 pb-5">
            <!-- Account Sidebar-->
            <div class="author-card pb-3">
                <div class="author-card-cover" style="background-image: url(https://demo.createx.studio/createx-html/img/widgets/author/cover.jpg);"></div>
                <div class="author-card-profile">
                    <div class="author-card-avatar">
                      <% if @user.avatar.attached? %>
                        <%= image_tag @user.avatar %>
                      <% else %>
                        <img src="http://bootdey.com/img/Content/avatar/avatar1.png" alt="Daniel Adams">
                      <% end %>
                      <%= form_tag user_avatar_index_path(@user.id), multipart: true do %>
                          <%= file_field_tag :avatar, class: "form-control" %>
                          <%= submit_tag "mettre à jour",class: "btn btn-primary" %>
                      <% end %>
                    </div>
                    <div class="author-card-details">
                        <h5 class="author-card-name text-lg"><%= @user.first_name %></h5><span class="author-card-position">Joined <%= @user.created_at %></span>
                    </div>
                </div>
            </div>
            <div class="wizard">
                <nav class="list-group list-group-flush">
                    <a class="list-group-item " href="/users/<%= @user.id %>">
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <div class="d-inline-block font-weight-medium text-uppercase"><i class="fa fa-shopping-bag mr-1 text-muted"> Vos commandes passés</i></div>
                            </div><span class="badge badge-secondary"><%= @user.orders.length %></span>
                        </div>
                    </a>
                    <a class="list-group-item active" href="/users/edit"><i class="fa fa-user text-muted"> Editer le profil</i></a>
                    <a class="list-group-item" href="/users/sign_out" data-method="delete"><i class="fa fa-user text-muted"></i> Déconnexion</a>
                </nav>
            </div>
        </div>
        <div class="row">
          <%= form_with(model: user, local: true) do |f| %>
            <% if user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

                <ul>
                <% user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="col-md-6">
              <div class="form-group">
                <label for="first_name">First name</label>
                <%= f.text_field :first_name, placeHolder: " First name", class: "form-control" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="last_name">Last name</label>
                <%= f.text_field :last_name, placeHolder: " Last name", class: "form-control" %>
              </div>
            </div>

            <div class="col-12">
                <hr class="mt-2 mb-3">
                  <div class="d-flex flex-wrap justify-content-between align-items-center">
                    <div class="custom-control custom-checkbox d-block">
                      <input class="custom-control-input" type="checkbox" id="subscribe_me" checked="">
                        <label class="custom-control-label" for="subscribe_me">S'abonner au Newsletter</label>
                    </div>  
                <%= f.submit "Save Changes", class: "btn btn-primary" %>
              </div>
            </div>

            </div>
          <% end %>
        </div>

    </div>
  </div>
</div>

app/views/users/edit.html.erb
<br><br><br><br><br><br>
<%= render 'form', user: @user %><br>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<br><br><br><br><br><br><br>
<p id="notice"><%= notice %></p>

<% unless @user.orders.length == 0 %>
	
<% end %>

<div class="container mb-4 main-container profil_division">
    <div class="row">
        <div class="col-lg-4 pb-5">
            <!-- Account Sidebar-->
            <div class="author-card pb-3">
                <div class="author-card-cover" style="background-image: url(https://demo.createx.studio/createx-html/img/widgets/author/cover.jpg);"></div>
                <div class="author-card-profile">
                    <div class="author-card-avatar">
                    	<%if @user.avatar.attached?%>
											  <%= image_tag @user.avatar, alt: 'avatar', id: 'avatar' %>
											<%else%>
					              <img src="http://bootdey.com/img/Content/avatar/avatar1.png" alt="Daniel Adams">
											  <div>=== No avatar yet ===</div>
											<%end%>
                    </div>
                    <div class="author-card-details">
                        <h5 class="author-card-name text-lg"><%= @user.first_name %> <%= @user.last_name %></h5><span class="author-card-position">Joined <%= @user.created_at %></span>
                    </div>
                </div>
            </div>
            <div class="wizard">
                <nav class="list-group list-group-flush">
                    <a class="list-group-item active" href="#">
                        <div class="d-flex justify-content-between align-items-center">
                            <div><i class="fa fa-shopping-bag mr-1 text-muted active"></i>
                                <div class="d-inline-block font-weight-medium text-uppercase">Vos commandes passés</div>
                            </div><span class="badge badge-secondary"><%= @user.orders.length %></span>
                        </div>
                    </a>
                    <a class="list-group-item" href="/users/edit"><i class="fa fa-user text-muted"> Editer le profil</i></a>
                    <a class="list-group-item" href="/users/sign_out" data-method="delete"><i class="fa fa-user text-muted"> Déconnexion</i></a>
                </nav>
            </div>
        </div>
        <!-- Orders Table-->
        <div class="col-lg-8 pb-5">
            	
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                        <tr>
                            <th>Numéro de vente</th>
                            <th>Date d'achat</th>
                            <th>Etat</th>
                            <th>Total</th>	
                        </tr>
                    </thead>
                    <tbody>
                    	<%  
                    		@total = 0
                    		@user.orders.each do |order|
                    			order.cart.items.each do |item|	
                    				@total += item.price
                    			end
                    		end
                    	%>
                    	<% @user.orders.each do |order| %>
                    		<tr>
                    			<td><a class="navi-link" href="#order-details" data-toggle="modal"><%= order.stripe_customer_id %></a></td>
                    			<td><%= order.created_at %></td>
                    			<td><span class="badge badge-success m-0"><%= 'Done' if order.status %></span></td>
                    			<td><span>$<%= @total %></span></td>
                    		</tr>
                    	<% end %>
                        <!-- <tr>
                            <td><a class="navi-link" href="#order-details" data-toggle="modal">78A643CD409</a></td>
                            <td>August 08, 2017</td>
                            <td><span class="badge badge-danger m-0">Canceled</span></td>
                            <td><span>$760.50</span></td>
                        </tr>
                        <tr>
                            <td><a class="navi-link" href="#order-details" data-toggle="modal">34VB5540K83</a></td>
                            <td>July 21, 2017</td>
                            <td><span class="badge badge-info m-0">In Progress</span></td>
                            <td>$315.20</td>
                        </tr>
                        <tr>
                            <td><a class="navi-link" href="#order-details" data-toggle="modal">112P45A90V2</a></td>
                            <td>June 15, 2017</td>
                            <td><span class="badge badge-warning m-0">Delayed</span></td>
                            <td>$1,264.00</td>
                        </tr>
                        <tr>
                            <td><a class="navi-link" href="#order-details" data-toggle="modal">28BA67U0981</a></td>
                            <td>May 19, 2017</td>
                            <td><span class="badge badge-success m-0">Delivered</span></td>
                            <td>$198.35</td>
                        </tr>
                        <tr>
                            <td><a class="navi-link" href="#order-details" data-toggle="modal">502TR872W2</a></td>
                            <td>April 04, 2017</td>
                            <td><span class="badge badge-success m-0">Delivered</span></td>
                            <td>$2,133.90</td>
                        </tr>
                        <tr>
                            <td><a class="navi-link" href="#order-details" data-toggle="modal">47H76G09F33</a></td>
                            <td>March 30, 2017</td>
                            <td><span class="badge badge-success m-0">Delivered</span></td>
                            <td>$86.40</td>
                        </tr> -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>