config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # namespace :admin do
    #   resources :users
    #   resources :carts
    #   resources :items
    #   resources :item_to_carts
    #   resources :orders

    #   root to: "users#index"
    # end
	devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show, :edit, :update] do
  	resources :avatar, only: [:create]
  	resources :carts, only: [:show]
  	resources :items do
  		resources :item_to_carts
  	end
    resources :order
  end

  resources :confirmation, only: [:new, :create]
  
  post '/confirmation/new', to: 'confirmation#create'
  get '/presentation/team'
	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_one :order

	has_many :item_to_carts
	has_many :items, through: :item_to_carts 
end

app/models/confirmation.rb
class Confirmation < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :item_to_carts
	has_many :carts, through: :item_to_carts

	validates :title, presence: true, length: { minimum: 5}
	validates :price, presence: true, numericality: true
	validates :description, presence: true, length: {minimum: 5, maximum: 500}
	validates :image_url, uniqueness: true, presence: true
end

app/models/item_to_cart.rb
class ItemToCart < ApplicationRecord
	belongs_to :item
	belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :cart
	validates :description, presence: true

	after_create :send_congratulation_email

  def send_congratulation_email
    UserMailer.congratulation_email(self.user).deliver_now
    AdminMailer.admin_email(self.user).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :orders
  has_one_attached :avatar

  after_create :send_confirmation_email

  # after_create :send_welcome_email

  def send_confirmation_email
    unless self.is_validate
      UserMailer.confirmation_email(self).deliver_now
    end
  end

  def send_welcome_email
  	unless self.is_validate
      UserMailer.welcome_email(self).deliver_now
    end
  end
end

app/controllers/admin/carts_controller.rb
module Admin
  class CartsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Cart.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Cart.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avatar_controller.rb
class AvatarController < ApplicationController
  def create
  	@user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to user_path(@user.id)
    notice: 'Avatar successfully uploaded'
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	include CartsHelper
	include OrderHelper
	before_action :set_cart
	before_action :authenticate_user

	def show
		@items = compact(@cart)
		@user = User.find(params[:user_id])
		@amount = amountTotal
		@itemToCartS = ItemToCart.where(cart_id: @user.carts.last.id)
	end

	private 
	def set_cart
		@cart = current_user.carts.last
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = current_user
  	@items = Item.all
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!, expect: [:index, :show]

	def new
		@item = Item.new
	end

	def show
    @id = params[:id]
    @item = Item.find(@id)
    @thisItemInCart = ItemToCart.where(cart_id: current_user.carts.last.id, item_id: @item.id)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
	include OrderHelper

	def new
		@user = User.find(params[:user_id])
		@amount = amountTotal
	end

	def create
		@user = User.find(params[:user_id])
		@cart = @user.carts.last
		begin
		# Amount in cents
		  @amount = amountTotal

		  customer = Stripe::Customer.create({
		    email: params[:stripeEmail],
		    source: params[:stripeToken]
		  })

		  charge = Stripe::Charge.create({
		    customer: customer.id,
		    amount: @amount,
		    description: 'Rails Stripe customer',
		    currency: 'usd'
		  })

		  @order = Order.new(
		  	user_id: @user.id,
		  	cart_id: @cart.id,
		  	description: 'You have got your cute kitties',
		  	stripe_customer_id: customer.id,
		  	status: true
		  )

		  if @order.save
		  	myCart = Cart.create(user_id: @user.id)
		  	
	      @user.carts << myCart
	      @user.save
	      
		  	redirect_to user_cart_path(@user.id, @cart.id)
		  end

		rescue Stripe::CardError => e
		  flash[:error] = e.message
		  redirect_to user_cart_path(@user.id, @cart.id)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  include UsersHelper
  before_action :authenticate_user
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.avatar.attach(params[:avatar]) if params[:avatar]
        format.html { redirect_to @user, notice: 'Users was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def authenticate_user
		unless current_user
			redirect_to '/'
		end
	end
end

app/helpers/avatar_helper.rb
module AvatarHelper
end

app/helpers/carts_helper.rb
module CartsHelper

	def authenticate_user
		unless @cart.id == current_user.carts.last.id
			redirect_to '/'
		end
	end

	def compact(cart)
		newcart = []
		cart.items.each do |item|
			newcart << item unless newcart.include?(item)
		end
		newcart
	end
end

app/helpers/item_to_carts_helper.rb
module ItemToCartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper

	def amountTotal
		amount = 0
		@user.carts.last.items.each do |item|
			amount += item.price
		end
		return amount.to_i
	end
end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def authenticate_user
		unless @user == current_user
			redirect_to '/'
		end
	end
end

app/views/carts/show.html.erb
<!--================Home Banner Area =================-->
	<section class="banner_area">
		<div class="banner_inner d-flex align-items-center">
			<div class="container">
				<div class="banner_content text-center">
				</div>
			</div>
		</div>
	</section>
	<!--================End Home Banner Area =================-->

	<!--================Cart Area =================-->
	<section class="cart_area">
		<div class="container">
			<div class="cart_inner">
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th scope="col">Items</th>
								<th scope="col">Description</th>
								<th scope="col">Price</th>
								<th scope="col">Quantity</th>	
								<th scope="col">Total</th>
							</tr>
						</thead>
						<tbody>
							<% @items.each do |item| %>
							<tr>
								<td style="background-image: url('<%=item.image_url%>'); background-size: cover; color: white;">
									<div class="media">
										
										<div class="media-body">
											<p><%= item.title %></p>
										</div>
									</div>
								</td>
								<td>
									<div>
										<%= item.description %><br>
										<%= button_to 'remove', user_item_item_to_cart_path(@user.id, item.id, ItemToCart.where(item_id: item.id, cart_id: @user.carts.last.id).first.id), method: :delete, data: {confirm: "Are you sure ?"}, class: "btn btn-danger", remote: true %>
									</div>
								</td>
								<td>
									<h5>Ar <%= item.price %></h5>
								</td>
								<!-- <td>
									<div class="product_count">
										<input type="text" name="qty" id="sst" maxlength="12" value="1" title="Quantity:" class="input-text qty">
										<button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
										 class="increase items-count" type="button">
											<i class="lnr lnr-chevron-up"></i>
										</button>
										<button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
										 class="reduced items-count" type="button">
											<i class="lnr lnr-chevron-down"></i>
										</button>
									</div>
								</td> -->
								<td>
									<%= ItemToCart.where(cart_id: @user.carts.last.id, item_id: item.id).length %>
								</td>
								<td>
									<h5>$<%= item.price * ItemToCart.where(cart_id: @user.carts.last.id, item_id: item.id).length %></h5>
								</td>
							</tr>
							<% end %>

						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section>
	<!--================End Cart Area =================-->

	<center>
		<a id="transaction_info" class="gray_btn">
				About transaction 
		</a><br>

		<div class="collapse" id="info" style="text-align: center; display: inline-block;">
			<% unless @amount == 0 %>
				<center class="checkout_btn_inner">
					<%= render 'order/new', user: current_user %>			
				</center>
			<% else %>
				<div class="checkout_btn_inner">
					<h5>Your cats will apears here</h5>
				</div>
			<% end %>
			
			<h5>Number of kitty in my cart : <%= @cart.items.length %></h5>
		</div>
	</center>
	<% @itemToCartS.each do |itemToCart| %>
		<input type="hidden" name="itemToCart" id="<%= itemToCart.id %>">
	<% end %>